<a href="https://colab.research.google.com/github/AhmadAlabrash/machine-learning/blob/main/RO_GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [108]:
import pandas as pd
from sklearn.model_selection import GridSearchCV    
from sklearn.linear_model import LinearRegression 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.naive_bayes import MultinomialNB

In [109]:
df = pd.read_csv('sp.csv')

In [110]:
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
le =LabelEncoder()
df['spam'] = le.fit_transform(df.Category )
co =CountVectorizer()                                                                                        
y=df['spam']
x_co = co.fit_transform(df.Message)
x_co.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [111]:
clf =GridSearchCV(SVC(gamma='auto'),{
    'kernel':['rbf','liner'],
    'C':[1,10,20,30]
},return_train_score=False
)              
clf.fit(x_co,y)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning:
20 fits failed out of a total of 40.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py", line 342, in _sparse_fit
    kernel_type = self._sparse_kernels.index(kernel)
ValueError: 'liner' is not in list

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.86593699        nan 0.93808342        nan 0.96177263        nan
 0.96805323        nan]
  category=UserWarning,

GridSearchCV(estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'liner']})

In [112]:
clf.cv_results_

{'mean_fit_time': array([1.05208263, 0.00440798, 1.04052467, 0.0045001 , 0.98629169,
        0.00478883, 0.81609821, 0.00464277]),
 'std_fit_time': array([1.78495899e-02, 1.47242080e-04, 1.02290718e-02, 1.23323070e-04,
        1.53984669e-01, 3.72028473e-04, 4.21135677e-03, 8.86026315e-05]),
 'mean_score_time': array([0.25812712, 0.        , 0.25764017, 0.        , 0.22117648,
        0.        , 0.20189977, 0.        ]),
 'std_score_time': array([0.00320268, 0.        , 0.00597495, 0.        , 0.0048614 ,
        0.        , 0.00235382, 0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'liner', 'rbf', 'liner', 'rbf', 'liner', 'rbf',
                    'liner'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'liner'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'liner'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'liner'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'liner'}],
 'split0_test_score': array([0.86547085,        nan, 0.93721973,        nan, 0.96502242,
               nan, 0.97399103,        nan]),
 'split1_test_score': array([0.86547085,        nan, 0.93811659,        nan, 0.96143498,
               nan, 0.96950673,        nan]),
 'split2_test_score': array([0.86624776,        nan, 0.93895871,        nan, 0.96319569,
               nan, 0.96947935,        nan]),
 'split3_test_score': array([0.86624776,        nan, 0.93447038,        nan, 0.95332136,
               nan, 0.95870736,        nan]),
 'split4_test_score': array([0.86624776,        nan, 0.94165171,        nan, 0.96588869,
               nan, 0.96858169,        nan]),
 'mean_test_score': array([0.86593699,        nan, 0.93808342,        nan, 0.96177263,
               nan, 0.96805323,        nan]),
 'std_test_score': array([0.0003806 ,        nan, 0.00233666,        nan, 0.00449591,
               nan, 0.00504041,        nan]),
 'rank_test_score': array([4, 5, 3, 6, 2, 7, 1, 8], dtype=int32)}

In [113]:
pd.DataFrame(clf.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.052083,0.017850,0.258127,0.003203,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.865471,0.865471,0.866248,0.866248,0.866248,0.865937,0.000381,4
1,0.004408,0.000147,0.000000,0.000000,1,liner,"{'C': 1, 'kernel': 'liner'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,1.040525,0.010229,0.257640,0.005975,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.937220,0.938117,0.938959,0.934470,0.941652,0.938083,0.002337,3
3,0.004500,0.000123,0.000000,0.000000,10,liner,"{'C': 10, 'kernel': 'liner'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
4,0.986292,0.153985,0.221176,0.004861,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.965022,0.961435,0.963196,0.953321,0.965889,0.961773,0.004496,2
5,0.004789,0.000372,0.000000,0.000000,20,liner,"{'C': 20, 'kernel': 'liner'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
6,0.816098,0.004211,0.201900,0.002354,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.973991,0.969507,0.969479,0.958707,0.968582,0.968053,0.005040,1
7,0.004643,0.000089,0.000000,0.000000,30,liner,"{'C': 30, 'kernel': 'liner'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,8

In [114]:
#we will ccccccchange dataset here
df=pd.read_csv('/content/titanic.csv')
df =df.dropna()

In [115]:
df_para ={
   'svm' :{ 'model': SVC(),
    'params':{
        'kernel':['rbf','liner'],
        'C':[1,20,30]
    }},
     'ra' :{ 'model': RandomForestClassifier(),
    'params':{
        'n_estimators':[5,10,15,20,25,30],
        'max_depth':[10,20,30]
    }}
    ,
     'nb' :{ 'model': MultinomialNB(),
    'params':{
        
        'alpha':[0.001,0.01,30]
    }}
}

In [120]:
res=[]
for useless ,mo in df_para.items() :
                    
    clf =GridSearchCV(mo['model'],mo['params'],cv=5,return_train_score=False)              
    clf.fit(df[['Parch','Pclass','Age']],df.Survived)
    res.append ({'bestParams':clf.best_params_ ,'bestscore':clf.best_score_})

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning:
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py", line 333, in _dense_fit
    random_seed=random_seed,
  File "sklearn/svm/_libsvm.pyx", line 173, in sklearn.svm._libsvm.fit
ValueError: 'liner' is not in list

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.67207207        nan 0.67747748        nan 0.67747748        nan]
  category=UserWarning,

In [121]:
pd.DataFrame(res)

                             bestParams  bestscore
0            {'C': 20, 'kernel': 'rbf'}   0.677477
1  {'max_depth': 10, 'n_estimators': 5}   0.694144
2                      {'alpha': 0.001}   0.672072